parameters:
- name: environment
  type: string
- name: subscriptionEndpoint
  type: string
- name: adfName
  type: string
- name: resourceGroup
  type: string
- name: adfOverrideParameters
  type: string
- name: adfFolder
  type: string
  default: ./
- name: deployparameterFileName
  type: string
jobs:
- deployment: deploy_adf
  displayName: 'Deploy to Azure Data factory'
  pool: Azure Pipelines

  environment: ${{parameters.environment}}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          path: 'self'
        - checkout: datafactory
          path: 'adf_publish'

        - task: CmdLine@2
          displayName: 'Prepare Az Environment'
          inputs:
            script: 'pwsh --command Install-module -Name Az.accounts -requiredVersion 2.1.2 -AllowClobber -Force'
        - task: AzurePowerShell@4
          displayName: 'Azure Powershell script: Stop Adf Triggers'
          inputs:
            azureSubscription: ${{parameters.subscriptionEndpoint}}
            Scriptpath: '$(Pipeline.Workspace)/self/_scripts/deploymentadf.ps1'
            Scriptarguments: '-armTemplate "$(Pipeline.Workspace)/adf_publish/${{ parameters.adfFolder }}/ARMTemplateForFactory.json" -ResourceGroupName "${{ parameters.resourceGroup}}" -DataFactoryName "${{ parameters.adfName}}" -predeployment $true'
            azurePowerShellVersion: LatestVersion
        - task: AzureResourceGroupDeployment@2
          displayName: 'Azure Deployment:Create or Update Resoruce Group action on ${{ parameters.resourceGroup}}'
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            resourceGroupName: ${{ parameters.resourceGroup }}
            location: '$(azureLocation)'
            csmFile: '$(Pipeline.Workspace)/adf_publish/${{ parameters.adfFolder }}/ARMTemplateForFactory.json'
            cdsmParametersFile: '$(Pipeline.Workspace)/self/armtemplate/${{ parameters.environment }}/${{ parameters.deployParameterFileName }}.json'
            overrideParameters: -fatoryName ${{ parameters.adfName }} ${{ parameters.adfOverrideParameters }}
        - task: AzurePowerShell@4
          displayName: 'Azure PowerShell Script: Start ADF triggers'
          inputs:
            azureSubscription: ${{parameters.subscriptionEndpoint}}
            Scriptpath: '$(Pipeline.Workspace)/self/_scripts/deploymentadf.ps1'
            Scriptarguments: '-armTemplate "$(Pipeline.Workspace)/adf_publish/${{ parameters.adfFolder }}/ARMTemplateForFactory.json" -ResourceGroupName "${{ parameters.resourceGroup}}" -DataFactoryName "${{ parameters.adfName}}" -predeployment $false'
            azurePowerShellVersion: LatestVersion